#!/bin/bash

if [ "$1" = "" ]; then
  cd ~/tsystem/bin
  ./apt-install.sh
  exit
fi
ignore ~/tsystem/apt.txt $1
echo "$1" >> ~/tsystem/apt.txt
sudo apt install $1
if [ "$2" != "" ]; then
  tsys-install ${@:2}
fi
sort ~/tsystem/apt.txt > ~/tsystem/apt_tmp.txt
mv ~/tsystem/apt_tmp.txt ~/tsystem/apt.txt
