#!/bin/bash

cd ~/tsystem-mods

cd $1

apt=`command -v apt`
brew=`command -v brew`
yum=`command -v yum`
if [ "$brew" != "" ]; then
  if [ -e package.txt ]; then
    brew uninstall `cat package.txt`
  fi
  if [ -e uninstall ]; then
    bash uninstall
  fi
  cd ..
  rm -rf $1
  brew install `tsys-package-list`
  exit
elif [ "$apt" != "" ]; then
  if [ -e package.txt ]; then
    sudo apt remove `cat package.txt`
  fi
  if [ -e uninstall ]; then
    bash uninstall
  fi
  cd ..
  rm -rf $1
  sudo apt install `tsys-package-list`
  sudo apt autoremove -y
  exit
elif [ "$yum" != "" ]; then
  if [ -e package.txt ]; then
    sudo yum remove `cat package.txt`
  fi
  if [ -e uninstall ]; then
    bash uninstall
  fi
  cd ..
  rm -rf $1
  sudo yum install `tsys-package-list`
  sudo apt autoremove -y
  exit
fi
