#!/usr/bin/env python

import sys
import subprocess
import os

args = sys.argv

res = subprocess.Popen(
    "tsys version", stdout=subprocess.PIPE, shell=True).communicate()[0]
res = res.decode("utf-8")
res = res.replace("\n", "")
ns = res.split(".")
n = str(ns[0]) + str(ns[1]) + str(ns[2])
n = int(n)
n = n + 1
h = int(n / 100)
t = int((n - h * 100) / 10)
o = int(n - (h * 100) - (t * 10))
next_version = str(h) + "." + str(t) + "." + str(o)
os.system("tsys version change " + next_version)
os.system("tsys commit")
os.system("tsys push")
