#!/bin/bash

brew=`command -v brew`
apt=`command -v apt`
yum=`command -v yum`
if [ "$brew" != "" ]; then
  brew uninstall $1
elif [ "$apt" != "" ]; then
  sudo apt remove $1
elif [ "$yum" != "" ]; then
  sudo yum remove $1
fi
ignore ~/tsystem/package.txt $1
if [ "$2" != "" ]; then
  tsys-remove ${@:2}
fi
