#!/bin/bash

cd ~/tsystem-mods
github=`cat ~/tsystem/github-id.txt`

if [ "$1" = "" ]; then
  mods=`cat ~/tsystem/mod-requirements.txt`
  if [ "$mods" != "" ]; then
    tsys mod install $mods
  fi
  exit
fi
if [ ! -d $1 ]; then
  git clone git@github.com:$github/tsystem-mod-$1.git $1
  if [ -e $1/package.txt ]; then
    apt=`command -v apt`
    yum=`command -v yum`
    brew=`command -v brew`
    if [ "$brew" != "" ]; then
      brew install `cat $1/package.txt`	   
    elif [ "$apt" != "" ]; then
      sudo apt install `cat $1/package.txt`
    elif [ "$yum" != "" ]; then
      sudo yum install `cat $1/package.txt`
    fi
  fi
  if [ -d $1/migration ]; then
    cd $1/migration
    files=($(ls))
    touch ../migrated.txt
    for f in "${files[@]}"
    do
      if [ "`cat ../migrated.txt | grep $f`" = "" ]; then
        echo "execute $f"
        bash $f
        echo $f >> ../migrated.txt
      fi
    done
  fi
fi
if [ "$2" != "" ]; then
  tsys mod install ${@:2}
fi
