#!/bin/bash

if [ "$1" = "" ]; then
  cd ~/tsystem/bin
  ./package-install.sh
  exit
fi
ignore ~/tsystem/package.txt $1
echo "$1" >> ~/tsystem/package.txt

brew=`command -v brew`
apt=`command -v apt`
if [ "$brew" != "" ]; then
  if [[ $1 == cask:* ]]; then
    brew install --cask `echo $1 | sed -e 's/cask://g'`
  fi
  brew install $1
elif [ "`uname`" != "Darwin" -a "$apt" != "" ]; then
  sudo apt install $1
fi
yum=`command -v yum`
if [ "$yum" != "" ]; then
  sudo yum install $1
fi

if [ "$2" != "" ]; then
  tsys-install ${@:2}
fi
sort ~/tsystem/package.txt > ~/tsystem/package_tmp.txt
mv ~/tsystem/package_tmp.txt ~/tsystem/package.txt
