#!/bin/bash

brew=`command -v brew`
apt=`command -v apt`
yum=`command -v yum`
if [ "$brew" != "" ]; then
  brew update
  brew upgrade
elif [ "$apt" != "" ]; then
  sudo apt update -y
  sudo apt upgrade -y
elif [ "$yum" != "" ]; then
  sudo yum update -y
fi

tsys pull async
tsys migrate
