#!/bin/bash

apt=`command -v apt`
if [ "$apt" != "" ]; then
  sudo apt update -y
  sudo apt upgrade -y
fi
yum=`command -v yum`
if [ "$yum" != "" ]; then
  sudo yum update -y
fi

tsys pull async
tsys migrate
